### ISSUE TITLE
Not working - Giving Error (Refer Logs)

### ISSUE THREAD

**Issue by parwalrahul** [adiralashiva8/pytest-live-results#1]
Refer Error Logs :

![image](https://user-images.githubusercontent.com/12759282/74599316-c13c4580-50a5-11ea-9334-f922f74fcd8e.png)
![image](https://user-images.githubusercontent.com/12759282/74599323-de711400-50a5-11ea-995d-e139aa787075.png)

**Comment by adiralashiva8** [comment]
Thanks for notifying, I have tested this in v2.7, Let me fix this

**Comment by adiralashiva8** [comment]
Fixed as part of commit -> 10c9e1c19b47c94f164818ddbe33523e62907c01
Changes are in new version v0.2

**Comment by adiralashiva8** [comment]
Use following command to install latest changes
`pip install git+https://github.com/adiralashiva8/pytest-live-results`
