### ISSUE TITLE
Need switch to enable / disable pytest-live-results

### ISSUE THREAD

**Issue by parwalrahul** [adiralashiva8/pytest-live-results#4]
Currently the pytest-live-results are generated if you once install this package.

Can we give a flag which enables / disable this.

**Need :** There may be scenarios where user might not be looking for any live log (smoke test run or single test run or while debugging)

**Comment by parwalrahul** [comment]
May be By-Default Off Mode would be a good option as majority of the time we do debugging instead of actual execution (especially when developing new tests).

**Comment by adiralashiva8** [comment]
Developed as part of commit: https://github.com/adiralashiva8/pytest-live-results/commit/68c44c8f2bd24501ad875b2f7dfa0a8003a5327b 

New argument called `--live` by default it is `False`, In order to enable live results users must specify `--live=True`

**Command**: `pytest --live:True`
