### ISSUE TITLE
Live Logs should not be generated when user just Collects the test using --collect-only option

### ISSUE THREAD

**Issue by parwalrahul** [adiralashiva8/pytest-live-results#5]
Live Logs File is generated even if we are only collecting the tests and not running them.

**Example :**
python -m pytest --collectonly

**Comment by adiralashiva8** [comment]
I feel #4 issue fixed this, because users must specify `--live=True` in order to generate live report so `--collect-only` doesnt generate live report.

What are your thoughts on this! We can close this if agree

**Comment by parwalrahul** [comment]
Agreed ! These are related. Closing this issue.
