### ISSUE TITLE
Filter for No of Tests in the Live Log result should not reset on Refresh

### ISSUE THREAD

**Issue by parwalrahul** [adiralashiva8/pytest-live-results#6]
The Filter (say 100 Tests View) should not be reset on Refresh as some analysis might be going on during that period on the Result Data.

**Comment by adiralashiva8** [comment]
Current implementation not supporting save previous selection, So I have added few more options like:

- `Export Results` (copy, csv, excel, print): Users can take a copy of results and start analysis until full execution is completed
- Result Per Page: `All` option to display all tests in page

**Comment by parwalrahul** [comment]
The Export Results  as CSV and Excel feature is not working. It is just stuck in the process phase.

![image](https://user-images.githubusercontent.com/12759282/76162236-c00cae80-6161-11ea-94ea-01907eb8d55b.png)

**Comment by adiralashiva8** [comment]
Fixed issue as part of https://github.com/adiralashiva8/pytest-live-results/commit/656584e9730769a96a2305617e997d2eb67d5815 commit, changes available in `v0.6`. Please confirm on this

**Comment by parwalrahul** [comment]
This is fixed. Closing this.
