### ISSUE TITLE
Live logs report should to be saved along with a datetime stamp for effective tracking and so that new execution does not erases old report

### ISSUE THREAD

**Issue by parwalrahul** [adiralashiva8/pytest-live-results#7]
datetime serves as a natural archival method for test teams.

**Comment by adiralashiva8** [comment]
Implemented as part of https://github.com/adiralashiva8/pytest-live-results/commit/656584e9730769a96a2305617e997d2eb67d5815 commit, changes available in `v0.6`. For usage please refer to [How to Implement](https://github.com/adiralashiva8/pytest-live-results#how-to-use-in-project) - Appending Timestamp section

New argument `--livetimestamp` helps in appending time stamp, by default value is `False`

**Comment by parwalrahul** [comment]
This looks good for our implementable use case.
Though, I am not sure if the default value for timestamp must be True or False.
Closing this issue.
