### ISSUE TITLE
[Documentation Error] Ambigous description for 'Appending Timestamp'

### ISSUE THREAD

**Issue by parwalrahul** [adiralashiva8/pytest-live-results#8]
Actual : Users can append timestamp to live report using following command 

Confusion :  User might feel that this is in reference to the timestamp inside the report.

Suggested Change in Text: User can append timestamp to the name of live report (Ex: pytest_live_dd_MMM_yy_hh_mm_ss) using following command.

**Comment by adiralashiva8** [comment]
Modified readme.md as suggested. Thank you :)
